export function defaultSections(aggregated = {}) {
  const data = {
    scannedSessions: 0,
    analyzedSessions: 0,
    projects: {},
    toolCounts: {},
    primarySuccess: {},
    friction: {},
    toolErrorCategories: {},
    averageResponseSeconds: 0,
    daysActive: 0,
    ...aggregated
  };
  const useChinese = data.userLanguage?.code === "zh";
  const topProject = Object.keys(data.projects)[0] || "your KimiCLI sessions";
  const topTool = Object.keys(data.toolCounts)[0] || "tools";
  const workflowItems = defaultWorkflowItems(data, useChinese ? "zh" : "en");
  const featureSuggestions = defaultFeatureSuggestions(data, useChinese ? "zh" : "en");
  const usagePatterns = defaultUsagePatterns(data, useChinese ? "zh" : "en");
  const skillOpportunities = defaultSkillOpportunities(data, useChinese ? "zh" : "en");
  if (useChinese) {
    return {
      schema_version: 1,
      at_a_glance: {
        whats_working: `已扫描 ${data.scannedSessions} 个 session，分析 ${data.analyzedSessions} 个。主要活动集中在 ${topProject}。`,
        whats_hindering: renderMap(data.toolErrorCategories) || "metrics-only 模式下没有看到稳定的工具错误模式。",
        quick_wins: `最高频工具是 ${topTool}。需要叙事分析时，用 /skill:insights 让当前 Kimi agent 生成报告内容。`,
        ambitious_workflows: "持续生成 insights，用它来迭代 skills、hooks、plan mode、subagents、Ralph 和 ultrawork。"
      },
      project_areas: {
        areas: projectAreas(data, "zh")
      },
      interaction_style: {
        narrative: `平均响应间隔：${formatSeconds(data.averageResponseSeconds)}。活跃天数：${data.daysActive}。`,
        key_pattern: "metrics-only 模式能识别节奏和工具使用，但更深的叙事模式需要当前 agent 生成。"
      },
      what_works: {
        intro: "从指标看，你已经有一些稳定有效的协作方式；叙事版报告会进一步解释这些模式为什么有效。",
        impressive_workflows: workflowItems
      },
      friction_analysis: {
        intro: renderMap(data.friction) || renderMap(data.toolErrorCategories) || "metrics-only 模式下没有发现明显摩擦模式。",
        categories: mapEntries(data.toolErrorCategories, 3, (category, count) => ({
          category,
          description: `${count} 次工具错误被归为这一类。`,
          examples: []
        }))
      },
      suggestions: {
        kimi_instructions_additions: instructionAdditions(data, "zh"),
        features_to_try: featureSuggestions,
        usage_patterns: usagePatterns
      },
      skill_opportunities: skillOpportunities,
      on_the_horizon: {
        intro: "后续报告可以把使用模式连接到更高层的自动化，而不是只展示统计。",
        opportunities: horizonOpportunities(data, "zh")
      },
      fun_ending: {
        headline: "你的工作流已经开始反过来塑造工具",
        detail: `这批 session 里，最高频意图是 ${topIntent(data)}，最高频工具是 ${topTool}。即使没有叙事 pass，也能看出你在不断把临时协作沉淀成可复用机制。`
      }
    };
  }
  return {
    schema_version: 1,
    at_a_glance: {
      whats_working: `Scanned ${data.scannedSessions} sessions and analyzed ${data.analyzedSessions}. Most activity centers on ${topProject}.`,
      whats_hindering: renderMap(data.toolErrorCategories) || "No recurring tool-error pattern is visible in metrics-only mode.",
      quick_wins: `Top tool: ${topTool}. Use /skill:insights for a narrative report generated by the current Kimi agent.`,
      ambitious_workflows: "Use recurring reports to tune skills, hooks, plan mode, subagents, Ralph, and ultrawork."
    },
    project_areas: {
      areas: projectAreas(data, "en")
    },
    interaction_style: {
      narrative: `Average response time: ${formatSeconds(data.averageResponseSeconds)}. Active days: ${data.daysActive}.`,
      key_pattern: "Metrics-only mode can identify cadence and tool usage, but not deeper narrative patterns."
    },
    what_works: {
      intro: "The metrics already show a few stable collaboration patterns; the narrative skill can explain why they work.",
      impressive_workflows: workflowItems
    },
    friction_analysis: {
      intro: renderMap(data.friction) || renderMap(data.toolErrorCategories) || "No major friction pattern found in metrics-only mode.",
      categories: mapEntries(data.toolErrorCategories, 3, (category, count) => ({
        category,
        description: `${count} tool errors were categorized this way.`,
        examples: []
      }))
    },
    suggestions: {
      kimi_instructions_additions: instructionAdditions(data, "en"),
      features_to_try: featureSuggestions,
      usage_patterns: usagePatterns
    },
    skill_opportunities: skillOpportunities,
    on_the_horizon: {
      intro: "Future reports can connect usage patterns to higher-level automation instead of only showing counts.",
      opportunities: horizonOpportunities(data, "en")
    },
    fun_ending: {
      headline: "Your workflow is starting to shape the tooling back",
      detail: `The strongest intent is ${topIntent(data)}, and the top tool is ${topTool}. Even without a narrative pass, the sessions show repeated attempts to turn ad-hoc collaboration into reusable mechanisms.`
    }
  };
}

function projectAreas(data, language) {
  return Object.entries(data.projects || {})
    .slice(0, 5)
    .map(([name, value]) => ({
      name,
      session_count: Number(value?.sessions || 0),
      description:
        language === "zh"
          ? `${Number(value?.messages || 0)} 条用户消息，分布在 ${Number(value?.sessions || 0)} 个 session。`
          : `${Number(value?.messages || 0)} user messages across ${Number(value?.sessions || 0)} sessions.`
    }));
}

function defaultWorkflowItems(data, language) {
  const intents = data.workflowSignals?.prompt_intents || {};
  const items = [];
  if ((intents.review || 0) > 0) {
    items.push(
      language === "zh"
        ? {
            title: "审查驱动改进",
            description: `review 类请求出现 ${intents.review} 次。你倾向于先让 agent 读代码和找风险，再决定是否修复，这适合沉淀成 omk-review 或项目级审查规则。`
          }
        : {
            title: "Review-driven improvement",
            description: `Review-style prompts appeared ${intents.review} time(s). You often ask the agent to inspect code and identify risks before changing it, which is a good fit for review skills or project-level review rules.`
          }
    );
  }
  if ((intents.planning || 0) > 0) {
    items.push(
      language === "zh"
        ? {
            title: "先想清楚再动手",
            description: `planning 类请求出现 ${intents.planning} 次。你会在架构或复杂实现前追问方案边界，这和 KimiCLI plan mode 很契合。`
          }
        : {
            title: "Plan before changing",
            description: `Planning prompts appeared ${intents.planning} time(s). You ask for boundaries and tradeoffs before larger changes, which maps well to KimiCLI plan mode.`
          }
    );
  }
  if ((intents.implementation || 0) > 0 || data.totalFilesModified > 0) {
    items.push(
      language === "zh"
        ? {
            title: "从讨论落到文件",
            description: `这批 session 涉及 ${data.totalFilesModified || 0} 个文件和 ${data.totalLinesAdded || 0} 行新增。你的有效模式不是只聊天，而是让 agent 把结论落到仓库产物里。`
          }
        : {
            title: "Turning discussion into files",
            description: `These sessions touched ${data.totalFilesModified || 0} files and added ${data.totalLinesAdded || 0} lines. Your strongest pattern is pushing the agent from discussion into repository artifacts.`
          }
    );
  }
  if (!items.length) {
    items.push(
      language === "zh"
        ? {
            title: "数据仍在积累",
            description: "当前 session 还不够多，但已经能看到工具使用、项目分布和响应节奏。多跑几次后，叙事版报告会更有判断力。"
          }
        : {
            title: "Evidence is still forming",
            description: "There are not enough sessions for a strong pattern yet, but tool usage, project distribution, and response cadence are already measurable."
          }
    );
  }
  return items.slice(0, 3);
}

function instructionAdditions(data, language) {
  const repeated = data.userInstructionsToAssistant || [];
  if (repeated.length) {
    return repeated.slice(0, 3).map((item) =>
      language === "zh"
        ? {
            addition: item.instruction,
            why: `这条指令重复出现 ${item.count} 次，适合放进 AGENTS.md 或相关 skill，避免以后反复说明。`,
            prompt_scaffold: `请把这条稳定偏好加入合适的 AGENTS.md 或 skill：${item.instruction}`
          }
        : {
            addition: item.instruction,
            why: `This instruction appeared ${item.count} times, so it may belong in AGENTS.md or a relevant skill.`,
            prompt_scaffold: `Add this stable preference to the right AGENTS.md or skill: ${item.instruction}`
          }
    );
  }
  return [
    language === "zh"
      ? {
          addition: "把重复出现的审查、验证、计划偏好沉淀到 AGENTS.md 或 skill 中。",
          why: "当前没有检测到完全重复的首轮指令，但任务意图已经显示出稳定偏好。",
          prompt_scaffold: "请根据最近的 insights 报告，帮我把重复偏好整理成 AGENTS.md 或 skill 规则。"
        }
      : {
          addition: "Move repeated review, verification, and planning preferences into AGENTS.md or skills.",
          why: "No exact repeated first prompt was detected yet, but the intent distribution already shows stable preferences.",
          prompt_scaffold: "Use the latest insights report to turn repeated preferences into AGENTS.md or skill rules."
        }
  ];
}

function defaultFeatureSuggestions(data, language) {
  const intents = data.workflowSignals?.prompt_intents || {};
  const mentions = data.workflowSignals?.feature_mentions || {};
  const suggestions = [
    language === "zh"
      ? {
          feature: "/skill:insights",
          one_liner: "让当前 Kimi agent 直接生成叙事报告。",
          why_for_you: "它避免嵌套 kimi --print，也能基于真实 session 反推出该沉淀哪些 skill/hook/AGENTS 指令。",
          example_code: "/skill:insights"
        }
      : {
          feature: "/skill:insights",
          one_liner: "Let the current Kimi agent write the narrative report directly.",
          why_for_you: "It avoids nested kimi --print and can turn real sessions into skill, hook, or AGENTS.md opportunities.",
          example_code: "/skill:insights"
        }
  ];
  if ((intents.review || 0) > 0 || (mentions.review || 0) > 0) {
    suggestions.push(
      language === "zh"
        ? {
            feature: "omk-review",
            one_liner: "把审查输出固定到项目的 .omk 文件夹。",
            why_for_you: "review 是高频意图时，固定格式和证据位置能减少每次重新解释标准。",
            example_code: "/skill:omk-review"
          }
        : {
            feature: "omk-review",
            one_liner: "Keep review output under the project's .omk folder.",
            why_for_you: "When review is frequent, fixed evidence and output locations reduce repeated setup.",
            example_code: "/skill:omk-review"
          }
    );
  }
  if ((intents.autonomous_execution || 0) > 0 || (mentions.ralph || 0) > 0 || (mentions.ultrawork || 0) > 0) {
    suggestions.push(
      language === "zh"
        ? {
            feature: "Ralph / ultrawork",
            one_liner: "让长任务持续到 done 或 blocked，而不是半途总结。",
            why_for_you: "你的长任务里已经出现 Ralph/ultrawork 信号，适合把完成标准和验证证据固定下来。",
            example_code: "/skill:ultrawork <任务>"
          }
        : {
            feature: "Ralph / ultrawork",
            one_liner: "Keep long tasks running until done or blocked.",
            why_for_you: "Your longer sessions already mention Ralph or ultrawork, so completion criteria and evidence should be explicit.",
            example_code: "/skill:ultrawork <task>"
          }
    );
  }
  return suggestions.slice(0, 3);
}

function defaultUsagePatterns(data, language) {
  const errors = Number(data.totalToolErrors || 0);
  const patterns = [
    language === "zh"
      ? {
          title: "把大任务先切成计划",
          suggestion: "多文件或架构任务先用 plan mode，让执行边界更稳定。",
          detail: "当任务横跨多个模块时，先确认计划能减少后续反复修正；小任务仍可直接执行。",
          copyable_prompt: "先进入 plan mode，探索项目后给我一份可执行计划，确认后再改代码。"
        }
      : {
          title: "Plan large tasks first",
          suggestion: "Use plan mode for multi-file or architectural work.",
          detail: "When a task crosses module boundaries, a short approved plan reduces later correction; small tasks can still go straight to execution.",
          copyable_prompt: "Enter plan mode first, inspect the project, and give me an executable plan before editing."
        }
  ];
  if (errors > 0) {
    patterns.push(
      language === "zh"
        ? {
            title: "把失败转成下一步证据",
            suggestion: "工具失败时要求 agent 记录失败原因和替代验证，而不是直接跳过。",
            detail: `${errors} 次工具错误说明 report 应该把失败也当作工作流信号，用来优化 hooks 或 skill。`,
            copyable_prompt: "如果工具失败，请记录失败命令、原因、替代检查，然后继续完成任务。"
          }
        : {
            title: "Turn failures into evidence",
            suggestion: "Ask the agent to record failed commands and alternate checks instead of skipping them.",
            detail: `${errors} tool errors mean failures should feed skill or hook improvements, not disappear from the workflow.`,
            copyable_prompt: "If a tool fails, record the command, reason, alternate check, and continue the task."
          }
    );
  }
  return patterns.slice(0, 3);
}

function defaultSkillOpportunities(data, language) {
  const intents = data.workflowSignals?.prompt_intents || {};
  const opportunities = [];
  if ((intents.review || 0) > 0) {
    opportunities.push(
      language === "zh"
        ? {
            name: "review-output-discipline",
            trigger: "用户要求 review、审查、检查潜在问题或提交前确认时",
            why: "review 是可复用工作流，适合把输出位置、证据格式和验证要求固定下来。",
            evidence: [`review intent: ${intents.review}`],
            proposed_scope: "更新 omk-review 或新增更窄的项目审查 skill。",
            risk: "过宽的 review skill 会变成噪声，必须绑定真实证据和 changed files。",
            example_prompt: "/skill:omk-review",
            recommended_action: "update_skill"
          }
        : {
            name: "review-output-discipline",
            trigger: "when the user asks for review, risk checks, or pre-commit validation",
            why: "Review is a reusable workflow that benefits from fixed output paths, evidence format, and verification rules.",
            evidence: [`review intent: ${intents.review}`],
            proposed_scope: "Update omk-review or create a narrower project-review skill.",
            risk: "A broad review skill becomes noise unless it is tied to real evidence and changed files.",
            example_prompt: "/skill:omk-review",
            recommended_action: "update_skill"
          }
    );
  }
  if ((intents.autonomous_execution || 0) > 0) {
    opportunities.push(
      language === "zh"
        ? {
            name: "autonomous-completion-discipline",
            trigger: "用户要求持续执行、Ralph、ultrawork 或任务完成后再停时",
            why: "长任务需要固定 done/blocked 状态、验证证据和继续策略。",
            evidence: [`autonomous_execution intent: ${intents.autonomous_execution}`],
            proposed_scope: "收紧 ultrawork 与 omk-ralph 的协作提示。",
            risk: "如果过度强制，会让小任务显得笨重。",
            example_prompt: "/skill:ultrawork <任务>",
            recommended_action: "update_skill"
          }
        : {
            name: "autonomous-completion-discipline",
            trigger: "when the user asks for Ralph, ultrawork, or keep-going execution",
            why: "Long tasks need explicit done/blocked state, verification evidence, and continuation rules.",
            evidence: [`autonomous_execution intent: ${intents.autonomous_execution}`],
            proposed_scope: "Tighten ultrawork and omk-ralph coordination prompts.",
            risk: "Over-enforcing this can make small tasks feel heavy.",
            example_prompt: "/skill:ultrawork <task>",
            recommended_action: "update_skill"
          }
    );
  }
  if (!opportunities.length) {
    opportunities.push(
      language === "zh"
        ? {
            name: "暂不创建新 skill",
            trigger: "当前证据不足以证明某个新 skill 有长期价值",
            why: "insights 应该减少噪声，而不是每次报告都制造新机制。",
            evidence: ["没有发现强重复意图"],
            proposed_scope: "继续积累 session，下次报告再判断。",
            risk: "过早创建 skill 会增加维护成本。",
            example_prompt: "/skill:insights",
            recommended_action: "no_action"
          }
        : {
            name: "do-not-create-a-new-skill-yet",
            trigger: "when evidence does not justify a durable new workflow",
            why: "Insights should reduce noise, not create a new mechanism on every report.",
            evidence: ["no strong repeated intent found"],
            proposed_scope: "Collect more sessions and decide in the next report.",
            risk: "Creating skills too early adds maintenance cost.",
            example_prompt: "/skill:insights",
            recommended_action: "no_action"
          }
    );
  }
  return opportunities.slice(0, 3);
}

function horizonOpportunities(data, language) {
  const topTool = Object.keys(data.toolCounts || {})[0] || "ReadFile";
  if (language === "zh") {
    return [
      {
        title: "由 insights 反向生成工作流",
        whats_possible: "当报告连续发现同类摩擦时，下一步不只是阅读建议，而是让 agent 直接起草 skill、hook 或 AGENTS.md 规则。",
        how_to_try: "运行 /skill:insights 后，只确认一个最强候选，让 agent 基于真实 session 数据改插件。",
        copyable_prompt: "基于这份 insights 报告，先只实现最有证据的一个 skill/hook 改进。"
      },
      {
        title: "计划模式与 Ralph 串联",
        whats_possible: "大任务先 plan，再由 Ralph/ultrawork 持续执行和验证，可以减少半途总结与遗漏。",
        how_to_try: "对多文件任务要求先 EnterPlanMode，确认后进入完成循环。",
        copyable_prompt: "这是一个大任务：先 plan，确认后用 Ralph/ultrawork 持续执行到 done 或 blocked。"
      },
      {
        title: "围绕高频工具优化提示",
        whats_possible: `${topTool} 是高频工具时，说明协作成本集中在读取、搜索或验证链路。可以把这些链路写成更短的项目规则。`,
        how_to_try: "把报告里最高频工具和错误类型作为 hook/skill 优化输入。",
        copyable_prompt: "根据 insights 的高频工具和错误类型，帮我优化一个最小的提示规则。"
      }
    ];
  }
  return [
    {
      title: "Generate workflows from insights",
      whats_possible: "When reports repeatedly find the same friction, the next step can be drafting a skill, hook, or AGENTS.md rule from real session evidence.",
      how_to_try: "Run /skill:insights, confirm one strongest candidate, and let the agent update the plugin.",
      copyable_prompt: "Based on this insights report, implement only the strongest evidence-backed skill or hook improvement."
    },
    {
      title: "Plan mode plus Ralph",
      whats_possible: "Large tasks can start with plan approval, then continue through Ralph or ultrawork until verified done or blocked.",
      how_to_try: "Ask for EnterPlanMode on multi-file tasks, then move into a completion loop after approval.",
      copyable_prompt: "This is a large task: plan first, then use Ralph/ultrawork until done or blocked."
    },
    {
      title: "Optimize around frequent tools",
      whats_possible: `When ${topTool} is the top tool, collaboration cost is probably concentrated in reading, searching, or verification. Those paths can become shorter project rules.`,
      how_to_try: "Use the most frequent tools and error categories as hook or skill optimization input.",
      copyable_prompt: "Use the insights top tools and error categories to propose one minimal prompt rule."
    }
  ];
}

function topIntent(data) {
  return Object.keys(data.workflowSignals?.prompt_intents || {})[0] || "general";
}

export function normalizeSections(value, aggregated = {}) {
  if (!isObject(value)) {
    throw new Error("insights sections must be a JSON object");
  }
  const fallback = defaultSections(aggregated);
  const sections = {
    schema_version: Number(value.schema_version || 1),
    at_a_glance: {
      whats_working: text(value.at_a_glance?.whats_working, fallback.at_a_glance.whats_working),
      whats_hindering: text(value.at_a_glance?.whats_hindering, fallback.at_a_glance.whats_hindering),
      quick_wins: text(value.at_a_glance?.quick_wins, fallback.at_a_glance.quick_wins),
      ambitious_workflows: text(
        value.at_a_glance?.ambitious_workflows,
        fallback.at_a_glance.ambitious_workflows
      )
    },
    project_areas: {
      areas: array(value.project_areas?.areas, fallback.project_areas.areas).map((area) => ({
        name: text(area?.name, "Unknown area"),
        session_count: number(area?.session_count, 0),
        description: text(area?.description, "")
      }))
    },
    interaction_style: {
      narrative: text(value.interaction_style?.narrative, fallback.interaction_style.narrative),
      key_pattern: text(value.interaction_style?.key_pattern, fallback.interaction_style.key_pattern)
    },
    what_works: {
      intro: text(value.what_works?.intro, fallback.what_works.intro),
      impressive_workflows: array(
        value.what_works?.impressive_workflows,
        fallback.what_works.impressive_workflows
      ).map((workflow) => ({
        title: text(workflow?.title, "Workflow"),
        description: text(workflow?.description, "")
      }))
    },
    friction_analysis: {
      intro: text(value.friction_analysis?.intro, fallback.friction_analysis.intro),
      categories: array(value.friction_analysis?.categories, fallback.friction_analysis.categories).map(
        (item) => ({
          category: text(item?.category, "Friction"),
          description: text(item?.description, ""),
          examples: array(item?.examples, []).map((example) => text(example, "")).filter(Boolean)
        })
      )
    },
    suggestions: {
      kimi_instructions_additions: array(
        value.suggestions?.kimi_instructions_additions,
        fallback.suggestions.kimi_instructions_additions
      ).map((item) => ({
        addition: text(item?.addition, ""),
        why: text(item?.why, ""),
        prompt_scaffold: text(item?.prompt_scaffold, "")
      })),
      features_to_try: array(value.suggestions?.features_to_try, fallback.suggestions.features_to_try).map(
        (item) => ({
          feature: text(item?.feature, ""),
          one_liner: text(item?.one_liner, ""),
          why_for_you: text(item?.why_for_you, ""),
          example_code: text(item?.example_code, "")
        })
      ),
      usage_patterns: array(value.suggestions?.usage_patterns, fallback.suggestions.usage_patterns).map(
        (item) => ({
          title: text(item?.title, ""),
          suggestion: text(item?.suggestion, ""),
          detail: text(item?.detail, ""),
          copyable_prompt: text(item?.copyable_prompt, "")
        })
      )
    },
    skill_opportunities: array(value.skill_opportunities, fallback.skill_opportunities).map((item) => ({
      name: text(item?.name, "Skill opportunity"),
      trigger: text(item?.trigger, ""),
      why: text(item?.why, ""),
      evidence: array(item?.evidence, []).map((entry) => text(entry, "")).filter(Boolean),
      proposed_scope: text(item?.proposed_scope, ""),
      risk: text(item?.risk, ""),
      example_prompt: text(item?.example_prompt, ""),
      recommended_action: normalizeAction(item?.recommended_action)
    })),
    on_the_horizon: {
      intro: text(value.on_the_horizon?.intro, fallback.on_the_horizon.intro),
      opportunities: array(
        value.on_the_horizon?.opportunities,
        fallback.on_the_horizon.opportunities
      ).map((item) => ({
        title: text(item?.title, ""),
        whats_possible: text(item?.whats_possible, ""),
        how_to_try: text(item?.how_to_try, ""),
        copyable_prompt: text(item?.copyable_prompt, "")
      }))
    },
    fun_ending: {
      headline: text(value.fun_ending?.headline, fallback.fun_ending.headline),
      detail: text(value.fun_ending?.detail, fallback.fun_ending.detail)
    }
  };
  validateSections(sections);
  return sections;
}

export function validateSections(sections) {
  if (!isObject(sections)) {
    throw new Error("insights sections must be a JSON object");
  }
  if (Number(sections.schema_version) !== 1) {
    throw new Error("insights sections schema_version must be 1");
  }
  for (const key of [
    "at_a_glance",
    "project_areas",
    "interaction_style",
    "what_works",
    "friction_analysis",
    "suggestions",
    "skill_opportunities",
    "on_the_horizon",
    "fun_ending"
  ]) {
    if (key === "skill_opportunities") {
      if (!Array.isArray(sections[key])) {
        throw new Error("insights sections missing array: skill_opportunities");
      }
    } else if (!isObject(sections[key])) {
      throw new Error(`insights sections missing object: ${key}`);
    }
  }
}

function renderMap(map, formatter = (value) => `${value}`) {
  return Object.entries(map || {})
    .slice(0, 8)
    .map(([key, value]) => `- ${key}: ${formatter(value)}`)
    .join("\n");
}

function formatSeconds(value) {
  if (!value) {
    return "n/a";
  }
  return `${Math.round(value)}s`;
}

function mapEntries(map, limit, mapper) {
  return Object.entries(map || {})
    .slice(0, limit)
    .map(([key, value]) => mapper(key, value));
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function text(value, fallback) {
  const string = String(value ?? "").trim();
  return string || fallback;
}

function number(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function array(value, fallback) {
  return Array.isArray(value) ? value : fallback;
}

function normalizeAction(value) {
  const action = text(value, "no_action");
  return [
    "create_skill",
    "update_skill",
    "add_hook",
    "add_agents_instruction",
    "no_action"
  ].includes(action)
    ? action
    : "no_action";
}
