export function defaultSections(aggregated = {}) {
  const data = {
    scannedSessions: 0,
    analyzedSessions: 0,
    projects: {},
    toolCounts: {},
    primarySuccess: {},
    friction: {},
    toolErrorCategories: {},
    averageResponseSeconds: 0,
    daysActive: 0,
    ...aggregated
  };
  const useChinese = data.userLanguage?.code === "zh";
  const topProject = Object.keys(data.projects)[0] || "your KimiCLI sessions";
  const topTool = Object.keys(data.toolCounts)[0] || "tools";
  if (useChinese) {
    return {
      schema_version: 1,
      at_a_glance: {
        whats_working: `已扫描 ${data.scannedSessions} 个 session，分析 ${data.analyzedSessions} 个。主要活动集中在 ${topProject}。`,
        whats_hindering: renderMap(data.toolErrorCategories) || "metrics-only 模式下没有看到稳定的工具错误模式。",
        quick_wins: `最高频工具是 ${topTool}。需要叙事分析时，用 /skill:insights 让当前 Kimi agent 生成报告内容。`,
        ambitious_workflows: "持续生成 insights，用它来迭代 skills、hooks、plan mode、subagents、Ralph 和 ultrawork。"
      },
      project_areas: {
        areas: projectAreas(data, "zh")
      },
      interaction_style: {
        narrative: `平均响应间隔：${formatSeconds(data.averageResponseSeconds)}。活跃天数：${data.daysActive}。`,
        key_pattern: "metrics-only 模式能识别节奏和工具使用，但更深的叙事模式需要当前 agent 生成。"
      },
      what_works: {
        intro: "成功模式需要当前 agent 的叙事分析补全。",
        impressive_workflows: mapEntries(data.primarySuccess, 3, (title, count) => ({
          title,
          description: `${count} 个 session 匹配这个模式。`
        }))
      },
      friction_analysis: {
        intro: renderMap(data.friction) || renderMap(data.toolErrorCategories) || "metrics-only 模式下没有发现明显摩擦模式。",
        categories: mapEntries(data.toolErrorCategories, 3, (category, count) => ({
          category,
          description: `${count} 次工具错误被归为这一类。`,
          examples: []
        }))
      },
      suggestions: {
        kimi_instructions_additions: [],
        features_to_try: [
          {
            feature: "OMK insights skill",
            one_liner: "运行 /skill:insights，让当前 Kimi agent 写叙事 sections。",
            why_for_you: "这样不会嵌套 kimi --print，也不会把 provider 限流风险放到外部命令里。",
            example_code: "/skill:insights"
          }
        ],
        usage_patterns: []
      },
      skill_opportunities: [
        {
          name: "insights-driven skill review",
          trigger: "当 insights 多次发现同类重复工作流时",
          why: "metrics-only 模式只能提示候选方向；叙事报告可以判断是否值得沉淀为 skill。",
          evidence: [],
          proposed_scope: "等待 /skill:insights 生成叙事 sections 后再决定。",
          risk: "证据不足时创建 skill 会增加噪声。",
          example_prompt: "/skill:insights",
          recommended_action: "no_action"
        }
      ],
      on_the_horizon: {
        intro: "后续报告可以把使用模式连接到更高层的自动化。",
        opportunities: [
          {
            title: "自主 review loop",
            whats_possible: "把 OMK insights、review、Ralph 和 ultrawork 组合起来，定位可复用的工作流缺口。",
            how_to_try: "积累几个真实复杂 session 后运行 /skill:insights。",
            copyable_prompt: "/skill:insights"
          }
        ]
      },
      fun_ending: {
        headline: "Metrics-only report",
        detail: "没有提供当前 agent 生成的 sections，所以跳过叙事结尾。"
      }
    };
  }
  return {
    schema_version: 1,
    at_a_glance: {
      whats_working: `Scanned ${data.scannedSessions} sessions and analyzed ${data.analyzedSessions}. Most activity centers on ${topProject}.`,
      whats_hindering: renderMap(data.toolErrorCategories) || "No recurring tool-error pattern is visible in metrics-only mode.",
      quick_wins: `Top tool: ${topTool}. Use /skill:insights for a narrative report generated by the current Kimi agent.`,
      ambitious_workflows: "Use recurring reports to tune skills, hooks, plan mode, subagents, Ralph, and ultrawork."
    },
    project_areas: {
      areas: projectAreas(data, "en")
    },
    interaction_style: {
      narrative: `Average response time: ${formatSeconds(data.averageResponseSeconds)}. Active days: ${data.daysActive}.`,
      key_pattern: "Metrics-only mode can identify cadence and tool usage, but not deeper narrative patterns."
    },
    what_works: {
      intro: "Success patterns require the current agent's narrative pass.",
      impressive_workflows: mapEntries(data.primarySuccess, 3, (title, count) => ({
        title,
        description: `${count} matching sessions.`
      }))
    },
    friction_analysis: {
      intro: renderMap(data.friction) || renderMap(data.toolErrorCategories) || "No major friction pattern found in metrics-only mode.",
      categories: mapEntries(data.toolErrorCategories, 3, (category, count) => ({
        category,
        description: `${count} tool errors were categorized this way.`,
        examples: []
      }))
    },
    suggestions: {
      kimi_instructions_additions: [],
      features_to_try: [
        {
          feature: "OMK insights skill",
          one_liner: "Run /skill:insights for the current Kimi agent to write the narrative sections.",
          why_for_you: "It avoids nested kimi --print calls and keeps rate limits under the active session.",
          example_code: "/skill:insights"
        }
      ],
      usage_patterns: []
    },
    skill_opportunities: [
      {
        name: "insights-driven skill review",
        trigger: "when insights repeatedly finds the same workflow pattern",
        why: "Metrics-only mode can point at candidates; the narrative pass should decide whether a skill is warranted.",
        evidence: [],
        proposed_scope: "Wait for /skill:insights to generate narrative sections before applying changes.",
        risk: "Creating skills from weak evidence adds noise.",
        example_prompt: "/skill:insights",
        recommended_action: "no_action"
      }
    ],
    on_the_horizon: {
      intro: "Future reports can connect usage patterns to higher-level automation.",
      opportunities: [
        {
          title: "Autonomous review loops",
          whats_possible: "Combine OMK insights with review, Ralph, and ultrawork to find repeatable workflow gaps.",
          how_to_try: "Use /skill:insights after several substantial sessions.",
          copyable_prompt: "/skill:insights"
        }
      ]
    },
    fun_ending: {
      headline: "Metrics-only report",
      detail: "Narrative ending skipped because no current-agent sections were provided."
    }
  };
}

function projectAreas(data, language) {
  return Object.entries(data.projects || {})
    .slice(0, 5)
    .map(([name, value]) => ({
      name,
      session_count: Number(value?.sessions || 0),
      description:
        language === "zh"
          ? `${Number(value?.messages || 0)} 条用户消息，分布在 ${Number(value?.sessions || 0)} 个 session。`
          : `${Number(value?.messages || 0)} user messages across ${Number(value?.sessions || 0)} sessions.`
    }));
}

export function normalizeSections(value, aggregated = {}) {
  if (!isObject(value)) {
    throw new Error("insights sections must be a JSON object");
  }
  const fallback = defaultSections(aggregated);
  const sections = {
    schema_version: Number(value.schema_version || 1),
    at_a_glance: {
      whats_working: text(value.at_a_glance?.whats_working, fallback.at_a_glance.whats_working),
      whats_hindering: text(value.at_a_glance?.whats_hindering, fallback.at_a_glance.whats_hindering),
      quick_wins: text(value.at_a_glance?.quick_wins, fallback.at_a_glance.quick_wins),
      ambitious_workflows: text(
        value.at_a_glance?.ambitious_workflows,
        fallback.at_a_glance.ambitious_workflows
      )
    },
    project_areas: {
      areas: array(value.project_areas?.areas, fallback.project_areas.areas).map((area) => ({
        name: text(area?.name, "Unknown area"),
        session_count: number(area?.session_count, 0),
        description: text(area?.description, "")
      }))
    },
    interaction_style: {
      narrative: text(value.interaction_style?.narrative, fallback.interaction_style.narrative),
      key_pattern: text(value.interaction_style?.key_pattern, fallback.interaction_style.key_pattern)
    },
    what_works: {
      intro: text(value.what_works?.intro, fallback.what_works.intro),
      impressive_workflows: array(
        value.what_works?.impressive_workflows,
        fallback.what_works.impressive_workflows
      ).map((workflow) => ({
        title: text(workflow?.title, "Workflow"),
        description: text(workflow?.description, "")
      }))
    },
    friction_analysis: {
      intro: text(value.friction_analysis?.intro, fallback.friction_analysis.intro),
      categories: array(value.friction_analysis?.categories, fallback.friction_analysis.categories).map(
        (item) => ({
          category: text(item?.category, "Friction"),
          description: text(item?.description, ""),
          examples: array(item?.examples, []).map((example) => text(example, "")).filter(Boolean)
        })
      )
    },
    suggestions: {
      kimi_instructions_additions: array(
        value.suggestions?.kimi_instructions_additions,
        fallback.suggestions.kimi_instructions_additions
      ).map((item) => ({
        addition: text(item?.addition, ""),
        why: text(item?.why, ""),
        prompt_scaffold: text(item?.prompt_scaffold, "")
      })),
      features_to_try: array(value.suggestions?.features_to_try, fallback.suggestions.features_to_try).map(
        (item) => ({
          feature: text(item?.feature, ""),
          one_liner: text(item?.one_liner, ""),
          why_for_you: text(item?.why_for_you, ""),
          example_code: text(item?.example_code, "")
        })
      ),
      usage_patterns: array(value.suggestions?.usage_patterns, fallback.suggestions.usage_patterns).map(
        (item) => ({
          title: text(item?.title, ""),
          suggestion: text(item?.suggestion, ""),
          detail: text(item?.detail, ""),
          copyable_prompt: text(item?.copyable_prompt, "")
        })
      )
    },
    skill_opportunities: array(value.skill_opportunities, fallback.skill_opportunities).map((item) => ({
      name: text(item?.name, "Skill opportunity"),
      trigger: text(item?.trigger, ""),
      why: text(item?.why, ""),
      evidence: array(item?.evidence, []).map((entry) => text(entry, "")).filter(Boolean),
      proposed_scope: text(item?.proposed_scope, ""),
      risk: text(item?.risk, ""),
      example_prompt: text(item?.example_prompt, ""),
      recommended_action: normalizeAction(item?.recommended_action)
    })),
    on_the_horizon: {
      intro: text(value.on_the_horizon?.intro, fallback.on_the_horizon.intro),
      opportunities: array(
        value.on_the_horizon?.opportunities,
        fallback.on_the_horizon.opportunities
      ).map((item) => ({
        title: text(item?.title, ""),
        whats_possible: text(item?.whats_possible, ""),
        how_to_try: text(item?.how_to_try, ""),
        copyable_prompt: text(item?.copyable_prompt, "")
      }))
    },
    fun_ending: {
      headline: text(value.fun_ending?.headline, fallback.fun_ending.headline),
      detail: text(value.fun_ending?.detail, fallback.fun_ending.detail)
    }
  };
  validateSections(sections);
  return sections;
}

export function validateSections(sections) {
  if (!isObject(sections)) {
    throw new Error("insights sections must be a JSON object");
  }
  if (Number(sections.schema_version) !== 1) {
    throw new Error("insights sections schema_version must be 1");
  }
  for (const key of [
    "at_a_glance",
    "project_areas",
    "interaction_style",
    "what_works",
    "friction_analysis",
    "suggestions",
    "skill_opportunities",
    "on_the_horizon",
    "fun_ending"
  ]) {
    if (key === "skill_opportunities") {
      if (!Array.isArray(sections[key])) {
        throw new Error("insights sections missing array: skill_opportunities");
      }
    } else if (!isObject(sections[key])) {
      throw new Error(`insights sections missing object: ${key}`);
    }
  }
}

function renderMap(map, formatter = (value) => `${value}`) {
  return Object.entries(map || {})
    .slice(0, 8)
    .map(([key, value]) => `- ${key}: ${formatter(value)}`)
    .join("\n");
}

function formatSeconds(value) {
  if (!value) {
    return "n/a";
  }
  return `${Math.round(value)}s`;
}

function mapEntries(map, limit, mapper) {
  return Object.entries(map || {})
    .slice(0, limit)
    .map(([key, value]) => mapper(key, value));
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function text(value, fallback) {
  const string = String(value ?? "").trim();
  return string || fallback;
}

function number(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function array(value, fallback) {
  return Array.isArray(value) ? value : fallback;
}

function normalizeAction(value) {
  const action = text(value, "no_action");
  return [
    "create_skill",
    "update_skill",
    "add_hook",
    "add_agents_instruction",
    "no_action"
  ].includes(action)
    ? action
    : "no_action";
}
