export function defaultSections(aggregated = {}) {
  const data = {
    scannedSessions: 0,
    analyzedSessions: 0,
    projects: {},
    toolCounts: {},
    primarySuccess: {},
    friction: {},
    toolErrorCategories: {},
    averageResponseSeconds: 0,
    daysActive: 0,
    ...aggregated
  };
  const topProject = Object.keys(data.projects)[0] || "your KimiCLI sessions";
  const topTool = Object.keys(data.toolCounts)[0] || "tools";
  return {
    schema_version: 1,
    at_a_glance: {
      whats_working: `Scanned ${data.scannedSessions} sessions and analyzed ${data.analyzedSessions}. Most activity centers on ${topProject}.`,
      whats_hindering: renderMap(data.toolErrorCategories) || "No recurring tool-error pattern is visible in metrics-only mode.",
      quick_wins: `Top tool: ${topTool}. Use /skill:insights for a narrative report generated by the current Kimi agent.`,
      ambitious_workflows: "Use recurring reports to tune skills, hooks, plan mode, subagents, Ralph, and ultrawork."
    },
    project_areas: {
      areas: Object.entries(data.projects || {})
        .slice(0, 5)
        .map(([name, value]) => ({
          name,
          session_count: Number(value?.sessions || 0),
          description: `${Number(value?.messages || 0)} user messages across ${Number(value?.sessions || 0)} sessions.`
        }))
    },
    interaction_style: {
      narrative: `Average response time: ${formatSeconds(data.averageResponseSeconds)}. Active days: ${data.daysActive}.`,
      key_pattern: "Metrics-only mode can identify cadence and tool usage, but not deeper narrative patterns."
    },
    what_works: {
      intro: "Success patterns require the current agent's narrative pass.",
      impressive_workflows: mapEntries(data.primarySuccess, 3, (title, count) => ({
        title,
        description: `${count} matching sessions.`
      }))
    },
    friction_analysis: {
      intro: renderMap(data.friction) || renderMap(data.toolErrorCategories) || "No major friction pattern found in metrics-only mode.",
      categories: mapEntries(data.toolErrorCategories, 3, (category, count) => ({
        category,
        description: `${count} tool errors were categorized this way.`,
        examples: []
      }))
    },
    suggestions: {
      kimi_instructions_additions: [],
      features_to_try: [
        {
          feature: "OMK insights skill",
          one_liner: "Run /skill:insights for the current Kimi agent to write the narrative sections.",
          why_for_you: "It avoids nested kimi --print calls and keeps rate limits under the active session.",
          example_code: "/skill:insights"
        }
      ],
      usage_patterns: []
    },
    on_the_horizon: {
      intro: "Future reports can connect usage patterns to higher-level automation.",
      opportunities: [
        {
          title: "Autonomous review loops",
          whats_possible: "Combine OMK insights with review, Ralph, and ultrawork to find repeatable workflow gaps.",
          how_to_try: "Use /skill:insights after several substantial sessions.",
          copyable_prompt: "/skill:insights"
        }
      ]
    },
    fun_ending: {
      headline: "Metrics-only report",
      detail: "Narrative ending skipped because no current-agent sections were provided."
    }
  };
}

export function normalizeSections(value, aggregated = {}) {
  if (!isObject(value)) {
    throw new Error("insights sections must be a JSON object");
  }
  const fallback = defaultSections(aggregated);
  const sections = {
    schema_version: Number(value.schema_version || 1),
    at_a_glance: {
      whats_working: text(value.at_a_glance?.whats_working, fallback.at_a_glance.whats_working),
      whats_hindering: text(value.at_a_glance?.whats_hindering, fallback.at_a_glance.whats_hindering),
      quick_wins: text(value.at_a_glance?.quick_wins, fallback.at_a_glance.quick_wins),
      ambitious_workflows: text(
        value.at_a_glance?.ambitious_workflows,
        fallback.at_a_glance.ambitious_workflows
      )
    },
    project_areas: {
      areas: array(value.project_areas?.areas, fallback.project_areas.areas).map((area) => ({
        name: text(area?.name, "Unknown area"),
        session_count: number(area?.session_count, 0),
        description: text(area?.description, "")
      }))
    },
    interaction_style: {
      narrative: text(value.interaction_style?.narrative, fallback.interaction_style.narrative),
      key_pattern: text(value.interaction_style?.key_pattern, fallback.interaction_style.key_pattern)
    },
    what_works: {
      intro: text(value.what_works?.intro, fallback.what_works.intro),
      impressive_workflows: array(
        value.what_works?.impressive_workflows,
        fallback.what_works.impressive_workflows
      ).map((workflow) => ({
        title: text(workflow?.title, "Workflow"),
        description: text(workflow?.description, "")
      }))
    },
    friction_analysis: {
      intro: text(value.friction_analysis?.intro, fallback.friction_analysis.intro),
      categories: array(value.friction_analysis?.categories, fallback.friction_analysis.categories).map(
        (item) => ({
          category: text(item?.category, "Friction"),
          description: text(item?.description, ""),
          examples: array(item?.examples, []).map((example) => text(example, "")).filter(Boolean)
        })
      )
    },
    suggestions: {
      kimi_instructions_additions: array(
        value.suggestions?.kimi_instructions_additions,
        fallback.suggestions.kimi_instructions_additions
      ).map((item) => ({
        addition: text(item?.addition, ""),
        why: text(item?.why, ""),
        prompt_scaffold: text(item?.prompt_scaffold, "")
      })),
      features_to_try: array(value.suggestions?.features_to_try, fallback.suggestions.features_to_try).map(
        (item) => ({
          feature: text(item?.feature, ""),
          one_liner: text(item?.one_liner, ""),
          why_for_you: text(item?.why_for_you, ""),
          example_code: text(item?.example_code, "")
        })
      ),
      usage_patterns: array(value.suggestions?.usage_patterns, fallback.suggestions.usage_patterns).map(
        (item) => ({
          title: text(item?.title, ""),
          suggestion: text(item?.suggestion, ""),
          detail: text(item?.detail, ""),
          copyable_prompt: text(item?.copyable_prompt, "")
        })
      )
    },
    on_the_horizon: {
      intro: text(value.on_the_horizon?.intro, fallback.on_the_horizon.intro),
      opportunities: array(
        value.on_the_horizon?.opportunities,
        fallback.on_the_horizon.opportunities
      ).map((item) => ({
        title: text(item?.title, ""),
        whats_possible: text(item?.whats_possible, ""),
        how_to_try: text(item?.how_to_try, ""),
        copyable_prompt: text(item?.copyable_prompt, "")
      }))
    },
    fun_ending: {
      headline: text(value.fun_ending?.headline, fallback.fun_ending.headline),
      detail: text(value.fun_ending?.detail, fallback.fun_ending.detail)
    }
  };
  validateSections(sections);
  return sections;
}

export function validateSections(sections) {
  if (!isObject(sections)) {
    throw new Error("insights sections must be a JSON object");
  }
  if (Number(sections.schema_version) !== 1) {
    throw new Error("insights sections schema_version must be 1");
  }
  for (const key of [
    "at_a_glance",
    "project_areas",
    "interaction_style",
    "what_works",
    "friction_analysis",
    "suggestions",
    "on_the_horizon",
    "fun_ending"
  ]) {
    if (!isObject(sections[key])) {
      throw new Error(`insights sections missing object: ${key}`);
    }
  }
}

function renderMap(map, formatter = (value) => `${value}`) {
  return Object.entries(map || {})
    .slice(0, 8)
    .map(([key, value]) => `- ${key}: ${formatter(value)}`)
    .join("\n");
}

function formatSeconds(value) {
  if (!value) {
    return "n/a";
  }
  return `${Math.round(value)}s`;
}

function mapEntries(map, limit, mapper) {
  return Object.entries(map || {})
    .slice(0, limit)
    .map(([key, value]) => mapper(key, value));
}

function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

function text(value, fallback) {
  const string = String(value ?? "").trim();
  return string || fallback;
}

function number(value, fallback) {
  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : fallback;
}

function array(value, fallback) {
  return Array.isArray(value) ? value : fallback;
}
